version: '3'
services:
  my-python-app:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    # volumes:
    #   - ./app:/app
